[package]
name = "intent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonky2 = "0.1.3"
plonky2_ecdsa = "0.1.0"
sha3 = "0.10.8"
