[package]
name = "segment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multihash = "0.18.1"
plonky2 = "0.1.3"
